


services:
  db: 
    image: "postgres:16-alpine"
    restart: always
    environment: 
      POSTGRES_USER: chirp_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chirp_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
   db_data:

         

   